//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AZSWebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Card
    {
        public int Id { get; set; }
        public int CardTypeId { get; set; }
        public string CardNumber { get; set; }
        public string CardExpDate { get; set; }
        public int Balance { get; set; }
        public int CardHolderId { get; set; }
    
        public virtual CardType CardType { get; set; }
        public virtual LoyalityCard LoyalityCard { get; set; }
    }
}
