//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AZSWebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pay
    {
        public int Id { get; set; }
        public string CardNumber { get; set; }
        public int CardHolderId { get; set; }
        public string Code { get; set; }
        public double Price { get; set; }
        public string OrganisationName { get; set; }
        public int StationId { get; set; }
        public string Token { get; set; }
    
        public virtual LoyalityCard LoyalityCard { get; set; }
    }
}
