//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AZSWebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Purchase
    {
        public int Id { get; set; }
        public int CardHolderId { get; set; }
        public string PurchaseDate { get; set; }
        public int GasStationId { get; set; }
        public string FuelType { get; set; }
        public int Value { get; set; }
        public double Cost { get; set; }
        public string PaymentType { get; set; }
    
        public virtual GasStation GasStation { get; set; }
        public virtual LoyalityCard LoyalityCard { get; set; }
    }
}
