//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AZSWebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StationFuel
    {
        public int Id { get; set; }
        public int GasStationId { get; set; }
        public string FuelTypeId { get; set; }
        public double Price { get; set; }
        public int AmountOfFuel { get; set; }
    
        public virtual GasStation GasStation { get; set; }
    }
}
